version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: tenis_postgres
    environment:
      POSTGRES_DB: tenis
      POSTGRES_USER: tenis_user
      POSTGRES_PASSWORD: tenis_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
